// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffee: {
        compile: {
          files: [
            {
              expand: true,
              cwd: 'src',
              src: '**/*.coffee',
              dest: 'target',
              ext: '.js'
            }
          ]
        }
      },
      coffeelint: {
        app: 'src/**/*.coffee'
      },
      watch: {
        files: ['Gruntfile.coffee', 'src/**/*.coffee'],
        tasks: ['coffeelint', 'coffee']
      }
    });
    grunt.loadNpmTasks('grunt-coffeelint');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    return grunt.registerTask('default', ['watch']);
  };

}).call(this);
